services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules # Protege los módulos internos

  stats:
    build: ./statistics-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend-v2:
    build: ./frontend-v2
    ports:
      - "3002:3002"
    depends_on:
      - backend
      - stats

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081" # Usamos el puerto 8082 del lado del host porque el 8081 ya lo usa stats
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local