name: PR Compliance

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, milestoned, demilestoned]

jobs:
  compliance:
    name: Compliance Check
    # Solo ejecutar cuando el PR NO sea un borrador (draft)
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Milestone
        env:
          MILESTONE: ${{ github.event.pull_request.milestone.number }}
        run: |
          echo "Milestone present: ${MILESTONE:-None}"
          if [ -z "$MILESTONE" ]; then
            echo "::error::El PR debe tener un Milestone asignado cuando está listo para revisión."
            exit 1
          fi
          echo "Milestone: OK"

      - name: Validate CHANGELOG.md
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          # Obtener la lista de archivos cambiados respecto a la rama base
          FILES=$(git diff origin/$BASE_REF...HEAD --stat)
          NUM_ARR=($(echo "$FILES" | tail -n 1 | grep -oE '[0-9]+'))
          PRODUCT=1

          for num in "${NUM_ARR[@]}"; do
            PRODUCT=$((PRODUCT * num))
          done

          SIZE=$(awk "BEGIN { print int(sqrt($PRODUCT)) }")
          echo "The size of this PR is $SIZE"
          
          # Verificar si CHANGELOG.md está en la lista (1 si existe, 0 si no)
          if echo "$FILES" | grep -qx "CHANGELOG.md"; then
            CHANGELOG_CHANGED=1
          else
            CHANGELOG_CHANGED=0
          fi

          # Validación de CHANGELOG (Solo en size >= 100)
          if [ "$SIZE" -ge 100 ]; then
            if [ "$CHANGELOG_CHANGED" -eq 0 ]; then
              echo "::error file=CHANGELOG.md::CHANGELOG.md debe actualizarse por el tamaño del PR $SIZE >= 100"
              exit 1
            fi
            echo "Validación de CHANGELOG: OK"
          else
            echo "Saltando validación de CHANGELOG"
          fi
