name: PR Compliance

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, milestoned, demilestoned]

jobs:
  compliance:
    name: Compliance Check
    # Solo ejecutar cuando el PR NO sea un borrador (draft)
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed files
        id: all-changed-files
        uses: tj-actions/changed-files@v45

      - name: Check CHANGELOG.md update
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: CHANGELOG.md

      - name: Debug Info
        run: |
          echo "Total changed files: ${{ steps.all-changed-files.outputs.all_changed_count }}"
          echo "Is CHANGELOG changed?: ${{ steps.changed-files.outputs.any_changed }}"

      - name: Validate CHANGELOG.md
        if: |
          fromJSON(steps.all-changed-files.outputs.all_changed_count) >= 3 &&
          steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "::error file=CHANGELOG.md::CHANGELOG.md debe estar actualizado para PRs con 3 o más archivos."
          echo "Error: CHANGELOG.md no ha sido modificado en un PR de ${{ steps.all-changed-files.outputs.all_changed_count }} archivos."
          exit 1

      - name: Validate Milestone
        if: github.event.pull_request.milestone == null
        run: |
          echo "::error::El PR debe tener un Milestone asignado cuando está listo para revisión."
          echo "Error: Milestone no asignado."
          exit 1
